### ISSUE TITLE
Specify LLVM versions in installation and usage instruction

### ISSUE THREAD

**Issue by abhishektiwari** [dtkerns/d2#6]
Got following warning during installation, please specify supported LLVM versions in installation and usage instruction to ensure users can follow the instructions when using LLVM versions < 19 or 19>=.

```
warning: due to a bug in LLVM versions < 19, you will need to add a -O1 (minimum) to CFLAGS in your applications makefiles
```

[For JOSS Review](https://github.com/openjournals/joss-reviews/issues/6825)

**Comment by dtkerns** [comment]
That's correct, please see issue #3. All versions of LLVM are supported. However, the original work was done under CentOS7 which was/is running LLVM version 3.4.2. (which still runs without issue) While "modernizing" to RHEL9 (which runs LLVM version 16.0.6) the loop bug was discovered and documented. Due to the nature/philosophy of RHEL, it is not likely RHEL 9 will ever go beyond the the 16 series. The LLVM bug was fixed in version 19. Thus, users running LLVM versions > 13 and < 19, will need to add the -O1 (minimum optimization level) in order to successfully get the loop output from the LLVM `opt` command.

**Comment by dtkerns** [comment]
Should I close this? I've been waiting for a comment/confirmation from the originator.

**Comment by abhishektiwari** [comment]
Give me another few days, I will give another try and get back to you.

**Comment by abhishektiwari** [comment]
Please close this.
